[package]
name = "quartz_publisher"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.19", features = ["derive"] }
confy = "0.6.1"
dirs = "5.0.1"
markdown-parser = "0.1.2"
serde = "1.0.210"
serde_yaml = "0.9.34"
